### ISSUE TITLE
Clarification on authorship

### ISSUE THREAD

**Issue by rljacobson** [RuleBasedIntegration/JOSS-Publication#3]
Could you clarify the role of Nasser M. Abbasi in authoring this submission? This author does not appear to be listed as an author in the associated repositories.

**Comment by halirutan** [comment]
@rljacobson In fact, Nasser does not appear in the commits of the software. Nevertheless, he is the one who runs the various *independent integration tests* for Rubi to compare it with other CAS. This is a very time-consuming job as he is trying to compare the built-in integrators of Mathematica, Maple, Maxima, Fricas, Sympy, and Giac/Xcas with the results of Rubi's Mathematica implementation. 

The whole suite runs several weeks, and through Nasser, we try to maintain a fair comparison between systems. This is indeed harder as one might expect. Only for Rub, Mathematica, and Maple we can create the detailed grading results as outlined on page 6 in [this test-report from Nassers page](https://www.12000.org/my_notes/CAS_integration_tests/reports/rubi_4_15_2/index.pdf). The hard part is to verify if a solution that is different from the optimal solution is indeed a correct antiderivative.

With this work, Nasser is highly intertwined with Rubi and ensures its quality. This is the reason why he is listed on https://github.com/RuleBasedIntegration as contributor and we believe he has earned authorship for the current manuscript.

**Comment by rljacobson** [comment]
I agree that including him as an author is completely appropriate. Thank you for the detailed explanation.
